### ISSUE TITLE
Error when starting container in file server_spawner.sh: #!/bin/bash: No such file or directory

### ISSUE THREAD

**Issue by sbruinsma** [Ortus-Solutions/docker-commandbox#23] opened 2018-06-26 10:35 UTC
Spinning up CommandBox 4 container shows error:

```bash
/root/.CommandBox/cfml/system/modules_app/server-commands/bin/server_spawner.sh: line 1: ﻿#!/bin/bash: No such file or directory
```

**Comment by jclausen** [comment] 2018-06-26 12:16
Thanks @sbruinsma !  This is actually a bug within the CommandBox program, that has been fixed in 4.1.0.  Once that version of CommandBox is released, that error should go away.  As such, I'm going to close this out.

cc/ @bdw429s

**Closed by jclausen** 2018-06-26 12:16 UTC

**Comment by bdw429s** [comment] 2018-06-26 16:22
Hi @sbruinsma , we discussed this back on June 15th in Slack.  I told you it was just a warning caused by a BOM marker and didn't hurt anything and that it was already fixed on the bleeding edge of CommandBox.

**Comment by sbruinsma** [comment] 2018-06-27 08:45
Hi @bdw429s, Yes I remember. I thought it was already fixed so that's why I raised the issue. We have tight monitoring on all output that contain errors and this one is popping up all the time. Glad to hear it's fixed!
