### ISSUE TITLE
non /app APP_DIR causes failure on 3.2.0 commandbox version

### ISSUE THREAD

**Issue by camshed** [Ortus-Solutions/docker-commandbox#55] opened 2021-01-06 18:59 UTC
When running the latest adobe2018 image with a different **APP_DIR** then **/app** the container fails to start up with the below error. 

```
poc_container          | Set verboseErrors = true
poc_container          | INFO: CF Engine set to adobe@2018.0.10+320417
poc_container          | INFO: Server Home Directory set to: /usr/local/lib/serverHome
poc_container          | WARN: Configuration did not detect any known mechanisms for changing the default password.  Your CF engine administrative password has been set to:
poc_container          | 1MIXFy9btRAJSwVZELcXGaM5rbzzedyiOGBXP0cH1rL3JQDfzJBAHIPy2AKol3wQNW6nCAkfBWcaBiu99ztUw
poc_container          | INFO: Generating server startup script
poc_container          |  √ | Starting Server
poc_container          |    | √ | Setting Server Profile to [production]
poc_container          | INFO: Starting server using genrated script: /usr/local/bin/startup.sh
poc_container          | mv: cannot stat './server-start.sh': No such file or directory
poc_container          | chmod: cannot access '/usr/local/bin/startup.sh': No such file or directory
poc_container          | /usr/local/lib/build/util/start-server.sh: line 109: /usr/local/bin/startup.sh: No such file or directory
poc_container exited with code 127

```
**docker-compose.yml** below (**NOTE**: you'll need either a ../cf_temp/ folder relative to the file). 

Changing the base image to use **ortussolutions/commandbox:adobe2018-3.1.0** and you will no longer see the error.

```
version: '3.7'

services:
  poc_container:
    image: ortussolutions/commandbox:adobe2018
    container_name: poc_container
    expose:
      - "8085"
    ports:
      - "8085"
    environment:
      PORT: 8085
      APP_DIR: /app/wwwroot
    volumes:
      - ../cf_temp:/app
    command: /bin/sh -c /usr/local/lib/build/run.sh
```

Looks likes line 105 / 116 of **build/util/start-server.sh** should not rely on the current folder not changing when calling the **box server start** command but not positive on that.

**Comment by cybersonic** [comment] 2021-01-13 13:46
I can also report that this happening to our build scripts. 
For example with docker file:
```
FROM ortussolutions/commandbox:latest
COPY ./ ${APP_DIR}/
RUN export FINALIZE_STARTUP=true;$BUILD_DIR/run.sh;unset FINALIZE_STARTUP
```
If you run the following (with an application in the /application folder)  and pass it as APP_DIR:
```
docker build  -t box_fail . 
docker run -e APP_DIR=/app/application box_fail
```
You get:
```
❯ ./run_fail.sh        
Sending build context to Docker daemon  71.17kB
Step 1/3 : FROM ortussolutions/commandbox:latest
 ---> c9b18d0405c6
Step 2/3 : COPY ./ ${APP_DIR}/
 ---> 2a278f9eaacd
Step 3/3 : RUN ${BUILD_DIR}/util/warmup-server.sh
 ---> Running in 3690d7918c68
Starting up container in test mode
Set verboseErrors = true
INFO: Server Home Directory set to: /usr/local/lib/serverHome
 √ | Starting Server
   | √ | Setting Server Profile to [production]

[INFO ] Runwar: Starting RunWAR 4.3.13
[INFO ] Java version 1.8.0.275 (requires >= 1.8)
[INFO ] Runwar: HTTP2 Enabled:false
[INFO ] Runwar: HTTP sslEnable:false
[INFO ] Runwar: HTTP ajpEnable:false
[INFO ] Runwar: HTTP warFile exists:true
[INFO ] Runwar: HTTP warFile isDirectory:true
[INFO ] Runwar: Starting background app [lucee 5.3.7+47] from: /usr/local/lib/CommandBox/lib/runwar-4.3.13.jar 
[INFO ] Starting in background -
Stopping app...
Stopped
Artifacts directory cleaned of '0' items.
Container successfully warmed up
==> Optimizing CommandBox...
Artifacts directory cleaned of '0' items.
==> CommandBox cleanup complete
Removing intermediate container 3690d7918c68
 ---> 42c55c8c3caf
Successfully built 42c55c8c3caf
Successfully tagged box_fail:latest
28b25e56edc25b17f2712034a8167175c355893e13c360ec2732f6c102f94968
Set verboseErrors = true
INFO: Server Home Directory set to: /usr/local/lib/serverHome
WARN: Configuration did not detect any known mechanisms for changing the default password.  Your CF engine administrative password has been set to:
xxx
INFO: Generating server startup script
 √ | Starting Server
   | √ | Setting Server Profile to [production]
INFO: Starting server using genrated script: /usr/local/bin/startup.sh
mv: cannot stat './server-start.sh': No such file or directory
chmod: cannot access '/usr/local/bin/startup.sh': No such file or directory
/usr/local/lib/build/util/start-server.sh: line 109: /usr/local/bin/startup.sh: No such file or directory
```
As a FYI, I get this with all different pre-warm methods

**Comment by jclausen** [comment] 2021-01-13 15:18
Mark,

I just tested your script with the latest version of the image and I’m not able to replicate this, but the dockerfile you have listed at the top of your email doesn’t match the commands that are executing in your `./run-fail.sh` script – which is using `warmup-server.sh` instead of `run.sh` - `warmup-server` does not have the finalization logic in it so it would never generate the finalized startup script.

If you want to do both, then your Dockerfile would need to be something like this:

FROM ortussolutions/commandbox:latest



COPY ./ ${APP_DIR}/

# This environment variable does not need to be unset
ENV FINALIZE_STARTUP=true



RUN export FINALIZE_STARTUP=true;$BUILD_DIR/util/warmup-server.sh;$BUILD_DIR/run.sh





I do, however, recommend the progressive build if you are finalizing and it greatly cuts down the final image size:

https://www.ortussolutions.com/blog/comandbox-docker-v300-images-released

( See the Multi-stage builds section )

Let me know how else I can help!



Jon

**Comment by camshed** [comment] 2021-01-14 03:51
@jclausen any word on the original bug? I simplified the original example and moved it to the below Dockerfile and am getting the same results.

```
FROM ortussolutions/commandbox:adobe2018
COPY ./ ${APP_DIR}/
ENTRYPOINT $BUILD_DIR/run.sh
```
and just run it with
```
docker build  -t box_fail . 
docker run -e APP_DIR=/app/application box_fail
```

**Comment by jclausen** [comment] 2021-01-14 14:28
I’m unable to replicate the issue below using your Dockerfile contents and a command with a nested APP_DIR.   You shouldn’t, however, need to declare `ENTRYPOINT` as that is already in the `CMD` of the image.

I suspect there’s something in your `server.json` file that is causing the container to fail startup. Could you provide the output of the `docker run` command using your Dockerfile and run command below?

Also, you may want to see the discussion on CFML slack regarding Mark’s resolution of the issue: https://cfml.slack.com/archives/C06TSRXCJ/p1610553535434100

Best,
Jon

**Comment by camshed** [comment] 2021-01-15 00:16
Thanks Jon. Output is below after I removed the ENTRYPOINT line from the Dockerfile (thank you!). 

I do not have a **server.json** file or anything else in the folder other then an empty **application** folder and the Dockerfile.

```
Set verboseErrors = true
INFO: CF Engine set to adobe@2018.0.10+320417
INFO: Server Home Directory set to: /usr/local/lib/serverHome
WARN: Configuration did not detect any known mechanisms for changing the default password.  Your CF engine administrative password has been set to:
PCWrcr5SOYsVOupoO33imw7MfSJcrvVlhk4woU65fu4ztWwr2vIk7bwG0hTU9EwAqqRUHyiTxacjrzfnIakg
INFO: Generating server startup script
 √ | Starting Server
   | √ | Setting Server Profile to [production]
INFO: Starting server using genrated script: /usr/local/bin/startup.sh
mv: cannot stat './server-start.sh': No such file or directory
chmod: cannot access '/usr/local/bin/startup.sh': No such file or directory
/usr/local/lib/build/util/start-server.sh: line 109: /usr/local/bin/startup.sh: No such file or directory
```

I get the same output if I adjust the Dockerfile to run off the latest commandbox as well (dockerfile below)

```
FROM ortussolutions/commandbox:latest
COPY ./ ${APP_DIR}/
#Hard Code our engine environment
ENV CFENGINE adobe@2018.0.10+320417

# WARM UP THE SERVER
RUN ${BUILD_DIR}/util/warmup-server.sh
```

Curious that you can't reproduce though, did your folder have an empty **application** folder in it as well as the Dockerfile?

**Comment by bcox24** [comment] 2021-01-15 18:11
This Dockerfile works...
```
FROM ortussolutions/commandbox:adobe2018-3.1.0
ENV APP_DIR /app/wwwroot
RUN mkdir -p /app/wwwroot
```

And this Dockerfile fails...
```
FROM ortussolutions/commandbox:adobe2018
ENV APP_DIR /app/wwwroot
RUN mkdir -p /app/wwwroot
```

**Comment by cybersonic** [comment] 2021-01-15 18:17
The line that I could track it to, but couldnt find a fix for was:
https://github.com/Ortus-Solutions/docker-commandbox/blob/development/build/util/start-server.sh#L107

This is asking to:
`mv ./server-start.sh $BIN_DIR/startup.sh`

But it cannot find `./server-start.sh` since we arent in the /build/util folder anymore 

I presume `server-start.sh` is a different script file than `start-server.sh` too but I couldn't find the former

**Comment by esolano7** [comment] 2021-01-22 14:50
I deleted all my local images and made a rebuild and the error showed up.

`INFO: Generating server startup script
√ | Starting Server
| √ | Setting Server Profile to [production]
| √ | Installing package [forgebox:fusionreactor@^8.0.0]
INFO: Starting server using genrated script: /usr/local/bin/startup.sh
mv: cannot stat './server-start.sh': No such file or directory
chmod: cannot access '/usr/local/bin/startup.sh': No such file or directory
/usr/local/lib/build/util/start-server.sh: line 109: /usr/local/bin/startup.sh: No such file or directory`

**Comment by jclausen** [comment] 2021-01-22 15:48
OK.  I think the issue here might be that the script is not being generated when a certain set of criteria are present in the `server.json` file. The major difference between image versions 3.1.0 and 3.2.0 is the enabling of "single server mode" by default - and @bcox24 's Dockerfile's examples demonstrate a difference in behavior..   https://commandbox.ortusbooks.com/embedded-server/single-server-mode

Let me do some debugging today and see if I can nail it down.  @bdw429s  - if you have any ideas on what might prevent the script from generating in single server mode, let me know and I can try to track it down.

**Comment by bdw429s** [comment] 2021-01-22 17:58
My guess is that the script is being generated, but in a different folder than you're expecting.  If the start has the `--verbose` flag, it should tell you where it was created right in the console output.  If the server was prewarmed with a web root elsewhere, the start script is likely going into the previously warmed web root since it's just starting the previous server again.  That's my guess anyway.

**Comment by esolano7** [comment] 2021-01-22 18:36
I was able to narrow it down to using the APP_DIR enviroment variable with anything else than /app. For example you can do: `docker run --rm -p 8080:8080 -e APP_DIR="/var" ortussolutions/commandbox:lucee5-3.1.0` and it works
If you do `docker run --rm -p 8080:8080 -e APP_DIR="/var" ortussolutions/commandbox:lucee5-3.2.0` it fails but it works if you use `APP_DIR="/app"` instead of `APP_DIR="/var"`

**Comment by jclausen** [comment] 2021-01-22 20:39
Update, if anyone is blocked on this:  The issue is definitely related to the new singleServerMode setting.  With that setting on, the generated script is written to wherever the current value of `$APP_DIR` is set.  With that setting off, the script is always written to the CWD ( which at that point in the script is `/app` ).

A workaround, for those of you using custom Dockerfiles would be to add this command to your Dockerfile:

```
RUN box config set server.singleServerMode=false
```

I'm going to be pushing up a fix for this and will post and close this story when it ( v3.2.1 ) is published.  Sorry this has dragged out for a bit.

**Comment by cybersonic** [comment] 2021-01-22 23:19
That’s amazing! Thank you so much for looking into this and bearing with us!

Mark Drew

**Comment by cybersonic** [comment] 2021-01-25 15:54
Just want to say that in the interim, the 
`RUN box config set server.singleServerMode=false`
is indeed working!

**Comment by dougcain** [comment] 2021-01-27 11:55
Just ran into this, I warm up my server which I guess defaults to /app. When I use the container I set web.webroot to a sub directory of /app in server.josn which is on a mapped volume. It breaks :(

If I create the webroot sub directory and set webroot to it before warming up the server it works. I have ended up with this in my dockerfile:

`RUN mkdir -p /app/webroot/
RUN box config set web.webroot=/app/webroot/

ENV CFENGINE=adobe@2018.0.10+320417
RUN ${BUILD_DIR}/util/warmup-server.sh`

Seems a bit weird to have to do this but it works with singleServerMode=true. I don't think I understand what command box is doing at the point the webroot is decided.

**Comment by jclausen** [comment] 2021-01-27 22:50
Forgot to update that v3.2.1 is available now, which resolves the above issue.  

On your last comment, @dougcain , that is actually a chicken/egg behavior caused by the fact that, the startup script changes to the APP_DIR when it starts up and, in single server mode, the startup file is written to the webroot.  If that webroot does not exist when the startup script generates the script to run the server, it will fail.

Doing a `mkdir -p /app/webroot` will resolve the chicken/egg issue.

**Comment by dougcain** [comment] 2021-01-28 09:12
@jclausen I'm using the JDK11 build, ortussolutions/commandbox:jdk11-3.2.0 is there but not ortussolutions/commandbox:jdk11-3.2.1, will this be auto built at some point?

**Comment by jclausen** [comment] 2021-01-28 13:01
@dougcain : Looks like I forgot to push the tag up to GitHub so the version build didn't kick off.  It is running now and should be ready within the hour: https://travis-ci.com/github/Ortus-Solutions/docker-commandbox/builds/215068257

The current version of `ortussolutions/commandbox:jdk11` is the 3.2.1 build, which was from this build: https://travis-ci.com/github/Ortus-Solutions/docker-commandbox/builds/214196434  ( when a tag is pushed to github, it kicks off the tag-based build )

**Comment by bennadel** [comment] 2022-12-24 11:16
I just ran into this issue on `FROM ortussolutions/commandbox:lucee-light`. In the start up it says:

```
Start script for shell [bash] generated at: /app/server-start.sh
... 
mv: cannot stat '/app/wwwroot/server-start.sh': No such file or directory
```

**Comment by jclausen** [comment] 2022-12-27 21:22
@bennadel Can you share the contents of your Dockerfile?  I'm using `lucee-light` to build a couple of images on the latest release and am unable to reproduce.

**Comment by bennadel** [comment] 2022-12-28 10:53
@jclausen I believe my `Dockerfile` literally just had the `FROM ortussolutions/commandbox:lucee-light` line in it, and nothing else. But, my `docker-compose.yml` file was defining that `APP_DIR: "/app/wwwroot"`, which is probably where I was running into issues. I now remember @bdw429s saying that the tagged containers had all the values hard-coded, so I was probably just trying to do dynamic stuff with a hard-coded image.

**Comment by carehart** [comment] 2022-12-28 14:00
@bennadel I wonder if there's a different problem and solution: it could be that the `FROM ortussolutions/commandbox:lucee-light` in your dockerfile had previously pulled an older version of that image to your local docker cache, such that you're not getting the newer (fixed) one. 

If you go to the command line and do a docker pull of that same image name, does it show pulling a new one? And if so, does your execution now work?

If so, note that you could also force cache reloading (for referenced images) when doing either the `docker build` (of your dockerfile) or the `docker compose` (of your compose file). They both support a `- - pull` argument, and there is even a `docker compose pull` that can make sense in some situations. 

I'm just guessing about things based on reading the replies here. Sorry to you both if I have somehow misread things.

**Comment by jclausen** [comment] 2022-12-28 14:39
OK.  I see the issue now, and it does have to do with a warmed up server.  Apparently, in single server mode - which is what the images all use, once you start a server with a specific `$APP_DIR`, then the startup script always gets placed in that initial directory.  You can change the webroot, however, as long as you don't reset the `APP_DIR` variable.

That looks like this:

```
FROM ortussolutions/commandbox:lucee-light
ENV BOX_SERVER_WEB_WEBROOT=/app/wwwroot
```

I am going to look in to this a bit more to see if I can find a workaround to this behavior.  Maybe @bdw429s can chime in as to whether the behavior around the location of the startup script is what we should expect.

**Comment by bennadel** [comment] 2022-12-29 14:37
@carehart I'm pretty sure I was working from scratch because I don't think I've ever tried to use the Lite version of Lucee before.

@jclausen that makes sense -- I keep forgetting that the tagged images have a lot of stuff "already set" for you.... No matter how many times @bdw429s tells me this is how it works 🤣 For now, I have things working with the `docker-compose.yml` providing most of the information and then just using the non-tagged base image.

```yaml
  lucee:
    build:
      context: "./docker/lucee/"
      dockerfile: "Dockerfile"
    ports:
      - "80:8080"
      - "8080:8080"
    volumes:
      - "./app:/app"
    environment:
      APP_DIR: "/app/wwwroot"
      BOX_SERVER_APP_CFENGINE: "lucee@5.3.10+97"
      BOX_SERVER_PROFILE: "development"
      cfconfig_adminPassword: "password"
      HEALTHCHECK_URI: "http://lucee:8080/healthcheck.cfm"
      LUCEE_CASCADE_TO_RESULTSET: "false"
      LUCEE_LISTENER_TYPE: "modern"
      LUCEE_PRESERVE_CASE: "true"
```

The one thing I haven't figured out how to do yet is use a "lite" version of Lucee for `BOX_SERVER_APP_CFENGINE`. I am never quite sure where to find the list of engines that CommandBox supports.

**Comment by bennadel** [comment] 2022-12-29 14:40
Hey all, I see that you re-opened this Issue. But, I feel like this is maybe more a misunderstanding on my end than a bug in the CB system. I did not intend to create more work.

**Comment by jclausen** [comment] 2022-12-29 15:12
@bennadel I'm opening it because, depending on the resolution to [COMMANDBOX-1544](https://ortussolutions.atlassian.net/browse/COMMANDBOX-1544), I will either have to update the images or update the documentation with caveats around the changing of `APP_DIR` on pre-warmed images.  It's all good. 🙂

**Comment by jclausen** [comment] 2023-02-28 20:04
This will be resolved in CommandBox 5.8.0 https://ortussolutions.atlassian.net/browse/COMMANDBOX-1544.  Once the image is bumped to that version, I will revisit.

**Comment by bennadel** [comment] 2023-03-06 11:04
Very cool! 🥳

**Comment by jclausen** [comment] 2023-03-11 18:32
Image version 3.7.0 was published yesterday.  This one should be resolved.

**Closed by jclausen** 2023-03-11 18:32 UTC
Labels: needs info
